# Generated by Django 3.2.23 on 2024-01-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('general', '一般ユーザー'), ('restaurant_owner', '飲食店オーナー'), ('farmer', '農家')], default='general', max_length=20),
        ),
    ]
