# Generated by Django 3.2.23 on 2024-01-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verified',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('general', '一般ユーザー'), ('restaurant_owner', '飲食店オーナー'), ('farmer', '農家')], default='general', max_length=20),
        ),
    ]
