# Generated by Django 3.2.23 on 2024-02-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240126_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('general', '一般ユーザー'), ('restaurant_owner', '飲食店オーナー'), ('farmer', '生産者')], default='general', max_length=20),
        ),
    ]
