# Generated by Django 3.2.23 on 2024-02-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_avatar.png', null=True, upload_to='profile_images/'),
        ),
    ]
