databases:
  - name: foodconnections_db
    region: singapore
    plan: free
    databaseName: foodconnections_db
    user: foodconnections_user

services:
  - type: web
    name: foodconnections
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn myapp.wsgi:application'
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: foodconnections_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true