# Generated by Django 3.2.23 on 2024-01-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodconnections', '0005_auto_20240115_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='画像'),
        ),
    ]
