# Generated by Django 3.2.23 on 2024-01-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodconnections', '0006_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='コメント'),
        ),
    ]
