# Generated by Django 3.2.23 on 2024-01-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodconnections', '0007_restaurant_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='catchphrase',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='キャッチコピー'),
        ),
    ]
