# Generated by Django 3.2.23 on 2024-01-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodconnections', '0010_auto_20240116_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address1',
            field=models.CharField(blank=True, max_length=40, verbose_name='都道府県'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address2',
            field=models.CharField(blank=True, max_length=40, verbose_name='市区町村番地'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address3',
            field=models.CharField(blank=True, max_length=40, verbose_name='建物名'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='zip_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='ruby',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='店名（かな）'),
        ),
    ]
