# Generated by Django 3.2.23 on 2024-01-26 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodconnections', '0011_auto_20240122_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='farmer_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='農家ID'),
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(blank=True, max_length=50, verbose_name='農場名')),
                ('catchphrase', models.CharField(max_length=30, null=True, verbose_name='キャッチコピー')),
                ('comment', models.TextField(max_length=250, verbose_name='コメント')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='農家')),
            ],
        ),
    ]
