# Generated by Django 3.2.23 on 2024-01-30 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodconnections', '0012_auto_20240127_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='farmer_id',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='foodconnections.farmer', verbose_name='農家'),
        ),
    ]
