# Generated by Django 3.2.23 on 2024-01-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodconnections', '0013_auto_20240130_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='farmer',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='farmer_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='農家ID'),
        ),
    ]
