# Generated by Django 3.2.23 on 2024-02-02 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodconnections', '0014_auto_20240130_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='farm_name',
            field=models.CharField(max_length=50, verbose_name='農場名 / 代表者名'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='農家ユーザー'),
        ),
    ]
