# Generated by Django 3.2.23 on 2024-02-04 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodconnections', '0015_auto_20240202_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='catchphrase',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='キャッチコピー'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='comment',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farm_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='農場名 / 代表者名'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farmer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL, verbose_name='農家ユーザー'),
        ),
    ]
