# Generated by Django 3.2.23 on 2024-02-05 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodconnections', '0016_auto_20240204_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='messages',
            field=models.TextField(blank=True, null=True, verbose_name='店長コメント'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farm_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='会社名 / 代表者名'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farmer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL, verbose_name='生産者ユーザー'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='店舗概要'),
        ),
    ]
