# Generated by Django 3.2.23 on 2024-02-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodconnections', '0017_auto_20240205_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, default='restaurant_images/no_image.png', null=True, upload_to='restaurant_images/', verbose_name='画像'),
        ),
    ]
