# Generated by Django 3.2.23 on 2024-02-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodconnections', '0019_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/no_image.png', null=True, upload_to='category_images/', verbose_name='画像'),
        ),
    ]
